version: '3.9'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/jlpt-notify
    env_file:
      - ./.env
    networks:
      - jlpt-notify
    restart: always

networks:
  jlpt-notify:
